name: Build and release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-lib:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          release: false
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-gstreamer
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gst-plugins-base
            mingw-w64-x86_64-gst-plugins-good
            mingw-w64-x86_64-gst-plugins-bad
            mingw-w64-x86_64-gst-plugins-ugly
            mingw-w64-x86_64-gst-libav
            zip
      
      - name: Building packages ……
        shell: msys2 {0}
        run: |
          mkdir clapper-dist
          meson setup builddir --prefix=$GITHUB_WORKSPACE/clapper-dist
          cd builddir && meson compile
          meson install 
          
          zip -r ../clapper-dev.zip ../clapper-dist/*

      - name: Set TAG_NAME
        shell: msys2 {0}
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            clapper-dev.zip
          tag_name: ${{ env.TAG_NAME }}
