on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: "Flatpak"
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    timeout-minutes: 600
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Docker
      run: |
        dnf -y install docker
    - name: Setup QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@master
      with:
        bundle: com.github.rafostar.Clapper.flatpak
        manifest-path: pkgs/flatpak/com.github.rafostar.Clapper.json
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}
        upload-artifact: false
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: clapper-flatpak-${{ matrix.arch }}
        path: com.github.rafostar.Clapper.flatpak
        if-no-files-found: error
