on:
  workflow_dispatch:

name: "Flatpak Nightly"
jobs:
  flatpak:
    name: "Flatpak"
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        include:
        - os: ubuntu-24.04
          arch: x86_64
        - os: ubuntu-24.04-arm
          arch: aarch64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    container:
      image: registry.fedoraproject.org/fedora
      options: --privileged
    steps:
    - name: Prepare
      run: |
        dnf install -y git git-lfs dbus-daemon flatpak flatpak-builder libappstream-glib ccache zstd xorg-x11-server-Xvfb
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
        flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk.Extension.rust-stable/${{ matrix.arch }}/24.08
        flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk.Extension.llvm18/${{ matrix.arch }}/24.08
        flatpak --system install -y --noninteractive flathub org.flatpak.Builder
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@master
      with:
        bundle: com.github.rafostar.Clapper.flatpak
        manifest-path: pkgs/flatpak/com.github.rafostar.Clapper-nightly.json
        repository-name: gnome-nightly
        repository-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
        cache-key: flatpak-builder-${{ github.sha }}-testing-${{ github.run_number }}
        arch: ${{ matrix.arch }}
        upload-artifact: false
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: clapper-flatpak-nightly-${{ matrix.arch }}
        path: com.github.rafostar.Clapper.flatpak
        if-no-files-found: error
